# <center>**Chapter 10 : Building Neural Networks with Pytorch**</center>

## **PyTorch Fundamentals**
**The core data structure of pytorch is a tensor. It's a multidimensional array with a shape and data type, used for numerical computations.**

In [1]:
import torch

In [2]:
X = torch.tensor([[1.0 , 4.0 , 7.0] , [2.0 , 3.0 , 6.0]])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [3]:
X.shape , X.dtype

(torch.Size([2, 3]), torch.float32)

In [6]:
# indexing in tensor works same as numpy arrays

X[0 , 1], X[: , 1]

(tensor(4.), tensor([4., 3.]))

In [7]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

**you can also convert a tensor to a numpy array using the ``numpy()``  method and create a tensor from a numpy array**

In [8]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [9]:
torch.tensor(np.array([[1. , 4. , 7.] , [2. , 3. , 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

**the default precision for floats in 32 bits in pytorch whereas its 64 bits in Numpy. Its generally better to use 32 bits in deep learning because this takes half the RAM and speeds up computations , and neural networks do not actually need the extra precision offered by 64 bit floats.** 

In [10]:
# you can use ``torch.FloatTensor()`` which automatically converts the array to 32 bits

torch.FloatTensor(np.array([[1. , 4. , 7.] , [2. ,3. , 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [11]:
# you can also modify a tensor in place using indexing and slicing as with a numpy array

X[: , 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [14]:
# the relu method applies the ReLU activation function in place by replacing all negative values with 0s

X.relu_()
X


tensor([[1., 0., 7.],
        [2., 0., 6.]])

#### **Tip : Pytorch's inplace operations are easy to spot at a glance because their name always ends with an underscore**

## **Hardware Acceleration**

In [19]:
torch.cuda.is_available()

True

In [15]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backend.mps.is_available():
    device = "mps"
else :
    device = "cpu"

In [18]:
M = torch.tensor([[1. , 2. , 3.] , [4. , 5. , 6.]])
M = M.to(device)

In [20]:
M.device

device(type='cuda', index=0)

In [21]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')